/**
 * dsh-safe — quarantine overlay generation.
 *
 * The overlay is a plain cordis patch-list: one `- id: <id>` + `disabled: true`
 * entry per quarantined plugin, plus comments carrying the reason. It is
 * passed to `dsh --profile <p> --patch <overlay>` so the broken entry is
 * disabled without ever editing the user's own patch files.
 */

import { quarantineMap } from "./state.mjs";

export function renderOverlay(quarantine, generatedAt = new Date().toISOString()) {
  const ids = Object.keys(quarantine).sort();
  if (ids.length === 0) return "";
  const lines = [
    "# dsh-safe quarantine overlay — generated by dsh-safe",
    `# ${generatedAt}`,
    "# Entries here are DISABLED because they failed the pre-boot import probe",
    "# (or because a previous boot crashed and safe mode was entered).",
    "# Fix the plugin, then re-enable with:  dsh-safe unquarantine <id>",
    "# (or delete this file and the matching <profile>.state.json section).",
    "",
  ];
  for (const id of ids) {
    const q = quarantine[id] ?? {};
    lines.push(`# reason: ${String(q.reason ?? "unknown").replace(/\n/g, " ")}`);
    lines.push(`- id: ${id}`);
    lines.push("  disabled: true");
    lines.push("");
  }
  return lines.join("\n");
}

/** Parse a quarantine overlay back into a registry map (best effort). */
export function parseOverlay(text) {
  const map = {};
  if (!text) return map;
  let currentId = null;
  let pendingReason = null;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    let m = line.match(/^# reason:\s*(.*)$/);
    if (m) {
      pendingReason = m[1].trim();
      continue;
    }
    m = line.match(/^- id:\s*(.+)$/);
    if (m) {
      // A reason comment always precedes its entry: attach it immediately.
      currentId = unquote(m[1]);
      map[currentId] = { name: "", reason: pendingReason ?? "unknown", at: null };
      pendingReason = null;
      continue;
    }
    m = line.match(/^disabled:\s*(true|false)$/);
    if (m && currentId !== null && m[1] !== "true") {
      // an explicitly re-enabled entry inside the overlay — drop it
      delete map[currentId];
    }
  }
  return map;
}

function unquote(value) {
  const v = value.trim();
  if ((v.startsWith("'") && v.endsWith("'")) || (v.startsWith('"') && v.endsWith('"'))) {
    return v.slice(1, -1);
  }
  return v;
}
