/**
 * dsh-plugin-devkit — plugin_new: generate a valid plugin skeleton.
 * Generation is scaffolding only; the pipeline (check → test_boot → install)
 * is enforced before anything touches the real profile.
 */

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const HOST_APPLY = `/**
 * %NAME% — host half.
 *
 * Cordis plugin entry. Rules from the DSH plugin skill:
 *  - no imports beyond plain ESM packages resolved by the loader;
 *  - every side effect must be owned by apply(ctx) and cleaned on dispose;
 *  - use ctx.get('service') for optional services, inject only hard deps.
 */
export const name = "%NAME%";

export const inject = []; // e.g. ['tools', 'systemPrompt'] when registering tools

export function apply(ctx, config = {}) {
  const logger = ctx.logger ?? console;
  logger.info?.(\`[%NAME%] plugin active\`);
  // Register tools with ctx.tools.register(defineTool({...})) when needed.
  // Subscribe to agent events with ctx.on('session/event', (session, event) => ...).
}
`;

const CLIENT_STUB = `/**
 * %NAME% — client half (browser). Stub only.
 * The browser half ships via package.json "dsh.client" + exports["./client"].
 */
export function apply() {}
`;

export function generateSkeleton({ name, dir, kind = "host" }) {
  if (!/^[a-z0-9][a-z0-9-]*$/.test(name)) {
    throw new Error(`invalid plugin name "${name}": use lowercase letters, digits and dashes only`);
  }
  const target = join(dir, name);
  if (existsSync(target)) throw new Error(`target already exists: ${target}`);
  const hasClient = kind === "client" || kind === "both";
  mkdirSync(join(target, "lib"), { recursive: true });

  const manifest = {
    name,
    version: "0.1.0",
    private: true,
    type: "module",
    description: `${name} — DSH plugin (generated by dsh-plugin-devkit)`,
    main: "lib/index.js",
    exports: {
      ".": "./lib/index.js",
      ...(hasClient ? { "./client": "./lib/client.js" } : {}),
      "./package.json": "./package.json",
    },
    license: "MIT",
  };
  if (hasClient) {
    manifest.dsh = { client: { platform: "web", inject: [] } };
  }
  writeFileSync(join(target, "package.json"), JSON.stringify(manifest, null, 2) + "\n", "utf8");
  writeFileSync(join(target, "lib", "index.js"), HOST_APPLY.replaceAll("%NAME%", name), "utf8");
  if (hasClient) {
    writeFileSync(join(target, "lib", "client.js"), CLIENT_STUB.replaceAll("%NAME%", name), "utf8");
  }
  writeFileSync(
    join(target, "README.md"),
    `# ${name}\n\nDSH 插件（由 dsh-plugin-devkit 生成）。\n\n开发流程：\n\n1. 实现 lib/index.js 的 apply(ctx)\n2. \`plugin_check\`（语法 + 导入探针）\n3. \`plugin_test_boot\`（隔离 home 完整启动）\n4. \`plugin_backup\`（真实 profile 快照）\n5. \`plugin_install\`（安全安装）\n`,
    "utf8"
  );
  return target;
}
